version: '3.6'
services:
  postgres:
    image: postgres:16-bookworm
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_USER=db_user
      - POSTGRES_DB=database
  rabbitmq:
    image: rabbitmq:3.12.12-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/apps/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/apps/rabbitmq/log/:/var/log/rabbitmq
  backend:
    build: .
    ports:
      - "8080:8080"
